export const demoOptions = {
  brands: [
    { value: "strauss", label: "Strauss" },
    { value: "rhone", label: "Rhone" },
    { value: "arcteryx", label: "Arc'teryx" },
    { value: "lululemon", label: "lululemon" },
    { value: "tommybahama", label: "Tommy Bahama" },
    { value: "travismathew", label: "TravisMathew" },
  ],
  audiences: [
    { value: "men", label: "Men" },
    { value: "women", label: "Women" },
    { value: "kids", label: "Kids" },
  ],
  collections: [
    "e.s.basics",
    "e.s.concrete",
    "e.s.e:pic",
    "e.s.iconic",
    "e.s.motion 2020",
    "e.s.motion ten",
    "e.s.t:aktik",
    "e.s.trail",
    "e.s.vintage",
    "Strauss x 1620",
    "Strauss x LA FC",
    "Strauss x Stuntmen's Association",
  ],
  activities: ["Hike", "Trail Run", "Rock", "Boulder", "Alpine"],
  features: [],
  shop_highlights: [
    "Best Sellers",
    "New Arrivals",
    "Topseller",
    "News",
    "New Color",
    "Spring Favorite",
    "STRAUSS Pick",
  ],
  colors: ["Black", "Blue", "Grey", "Red"],
  material_keywords: ["Cotton", "Nylon", "Polyester", "Elastane"],
  categories: [
    "Shirts",
    "Pants",
    "Outerwear",
    "Hoodies & Sweatshirts",
    "Shorts",
    "Leggings",
    "Thermal Layers",
  ],
  subcategories: [
    "T-Shirts",
    "Polos",
    "Long Sleeves",
    "Work Shirts",
    "High-Vis Shirts",
    "Kids Shirts",
    "Work Pants",
    "Cargo Pants",
    "Double-Front Pants",
    "Jeans",
    "Bibs, Coveralls & Overalls",
    "Kids Pants",
    "Work Shorts",
    "Cargo Shorts",
    "Women's Shorts",
    "Softshell Jackets",
    "Lightweight Jackets",
    "Winter Jackets",
    "Work Jackets",
    "Vests",
    "High-Vis Outerwear",
    "Kids Jackets",
    "Hoodies",
    "Crewnecks",
    "Full-Zip Sweatshirts",
    "Women's Hoodies & Sweatshirts",
    "Men's Thermal Layers",
    "Women's Thermal Layers",
    "Women's Leggings",
  ],
  price: { min: 0, max: 350 },
};

export const demoDashboard = {
  source: [
    "https://us.strauss.com",
    "https://www.rhone.com",
    "https://arcteryx.com/us/en",
  ],
  scraped_at: null,
  summary: {
    total_products: 307,
    brands: 1,
    categories: 7,
    average_price: 75.88,
    available_products: 290,
    collection_memberships: 259,
    named_collection_products: 255,
    unassigned_collection_products: 52,
    multi_collection_products: 4,
    overlap_memberships: 4,
    category_memberships: 320,
    multi_category_products: 13,
    category_overlap_memberships: 13,
    availability_rate: 94.5,
  },
  audiences: [
    { name: "Men", value: 242 },
    { name: "Women", value: 45 },
    { name: "Kids", value: 20 },
  ],
  collections: [
    { name: "e.s.e:pic", value: 58 },
    { name: "e.s.basics", value: 45 },
    { name: "e.s.iconic", value: 41 },
    { name: "e.s.vintage", value: 25 },
    { name: "e.s.trail", value: 23 },
    { name: "e.s.t:aktik", value: 22 },
    { name: "e.s.motion ten", value: 15 },
    { name: "e.s.concrete", value: 8 },
    { name: "e.s.motion 2020", value: 6 },
  ],
  categories: [
    { name: "Shirts", value: 118 },
    { name: "Pants", value: 89 },
    { name: "Outerwear", value: 52 },
    { name: "Hoodies & Sweatshirts", value: 34 },
    { name: "Shorts", value: 20 },
    { name: "Thermal Layers", value: 4 },
    { name: "Leggings", value: 3 },
  ],
  subcategories: [
    { name: "T-Shirts", value: 45 },
    { name: "Polos", value: 23 },
    { name: "High-Vis Shirts", value: 22 },
    { name: "Long Sleeves", value: 13 },
    { name: "Work Shirts", value: 13 },
    { name: "Kids Shirts", value: 10 },
  ],
  products: [],
};
