export const MARKET_SEGMENTS = [
  {
    id: "active",
    name: "Active",
    description: "Sport and training clothes",
    products: "Gym, running and team sport",
    fabric: "Wicking, 4-way stretch and durable",
    brands: ["LSKD"],
    closest: ["Gymshark", "Puma"],
    competitors: ["Nike", "Adidas", "Under Armour", "Puma", "New Balance", "ASICS", "Gymshark", "Decathlon Domyos"],
    map: { x: 66, y: 35 },
    points: [
      ["Nike", 76, 80], ["New Balance", 52, 66], ["ASICS", 80, 64], ["Adidas", 46, 54],
      ["LSKD", 66, 55, true], ["Under Armour", 56, 44], ["Puma", 36, 36],
      ["Gymshark", 70, 36], ["Decathlon Domyos", 24, 16],
    ],
  },
  {
    id: "athleisure",
    name: "Athleisure",
    description: "Sport-inspired clothes for everyday",
    products: "Yoga, studio, golf lifestyle and leggings",
    fabric: "Soft, stretch and premium feel",
    brands: ["Lululemon", "Rhone", "Travis Mathew"],
    closest: ["Nike", "Adidas", "Under Armour", "Lacoste"],
    competitors: ["Alo Yoga", "Vuori", "Nike", "Adidas", "Under Armour", "Lacoste", "Athleta", "Fabletics", "Gymshark"],
    map: { x: 68, y: 72 },
    points: [
      ["Lacoste", 28, 76], ["Alo Yoga", 63, 84], ["Lululemon", 78, 73, true],
      ["Travis Mathew", 40, 67, true], ["Rhone", 65, 61, true], ["Vuori", 46, 54],
      ["Nike", 86, 48], ["Athleta", 30, 47], ["Under Armour", 61, 45],
      ["Adidas", 55, 38], ["Fabletics", 40, 27], ["Gymshark", 70, 34],
    ],
  },
  {
    id: "casual",
    name: "Casual",
    description: "Everyday leisure wear, not for sport",
    products: "Polos, tees and resort shirts",
    fabric: "Soft, comfortable and good looking",
    brands: ["Tommy Bahama"],
    closest: ["Ralph Lauren", "Tommy Hilfiger"],
    competitors: ["Ralph Lauren", "Lacoste", "Tommy Hilfiger", "Vineyard Vines", "Levi's", "Uniqlo", "Zara", "Gap"],
    map: { x: 31, y: 62 },
    points: [
      ["Ralph Lauren", 18, 87], ["Lacoste", 36, 78], ["Tommy Bahama", 27, 66, true],
      ["Vineyard Vines", 10, 58], ["Tommy Hilfiger", 30, 50], ["Levi's", 21, 43],
      ["Zara", 40, 34], ["Gap", 10, 30], ["Uniqlo", 25, 20],
    ],
  },
  {
    id: "outdoor",
    name: "Outdoor",
    description: "Hiking, climbing and weather protection",
    products: "Shells, insulation and trail pants",
    fabric: "Waterproof, breathable and tough",
    brands: ["Arc'teryx"],
    closest: ["The North Face", "Patagonia"],
    competitors: ["Patagonia", "The North Face", "Mammut", "Salomon", "Helly Hansen", "Fjallraven", "Columbia", "Decathlon Quechua"],
    map: { x: 84, y: 17 },
    points: [
      ["Arc'teryx", 90, 95, true], ["Mammut", 75, 84], ["Fjallraven", 34, 81],
      ["Patagonia", 70, 72], ["Helly Hansen", 48, 70], ["The North Face", 60, 58],
      ["Salomon", 58, 46], ["Columbia", 48, 42], ["Decathlon Quechua", 38, 16],
    ],
  },
  {
    id: "corporate",
    name: "Corporate",
    description: "Work clothes and uniforms",
    products: "Workwear, office wear and branded uniforms",
    fabric: "Hard-wearing, easy care and repeatable",
    brands: ["Hakro", "Engelbert Strauss"],
    closest: ["Dickies", "Fristads", "Carhartt", "Snickers Workwear"],
    competitors: ["Carhartt", "Dickies", "Snickers Workwear", "Fristads", "Blaklader", "Kubler"],
    map: { x: 22, y: 80 },
    points: [
      ["Snickers Workwear", 63, 75], ["Fristads", 55, 68], ["Carhartt", 33, 63],
      ["Blaklader", 49, 57], ["Hakro", 28, 50, true], ["Kubler", 53, 50],
      ["Engelbert Strauss", 40, 40, true], ["Dickies", 25, 24],
    ],
  },
];

export const MARKET_BRAND_SUMMARY = [
  { brand: "Lululemon", segment: "Athleisure", closest: "Nike, Adidas", reason: "Global sportswear leaders serving the same yoga and training customer." },
  { brand: "Rhone", segment: "Athleisure", closest: "Under Armour, Nike", reason: "Global performance brands competing in men's training." },
  { brand: "Travis Mathew", segment: "Athleisure", closest: "Nike, Lacoste", reason: "Golf lifestyle brands selling a similar look." },
  { brand: "Tommy Bahama", segment: "Casual", closest: "Ralph Lauren, Tommy Hilfiger", reason: "Global premium casual and resort style." },
  { brand: "LSKD", segment: "Active", closest: "Gymshark, Puma", reason: "Global gym and sportswear brands at a similar price." },
  { brand: "Arc'teryx", segment: "Outdoor", closest: "The North Face, Patagonia", reason: "World-known premium outdoor brands." },
  { brand: "Hakro", segment: "Corporate", closest: "Dickies, Fristads", reason: "Established mid-price workwear brands." },
  { brand: "Engelbert Strauss", segment: "Corporate", closest: "Carhartt, Snickers Workwear", reason: "Well-known workwear names at a similar price." },
];
